name: FastAPI CI Pipeline Started

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV  

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t fastapi-demo:${IMAGE_TAG} .
      # ------------------------------------
      # Trivy securityScan
      # ------------------------------------
      
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master

        with: 
          image-ref: fastapi-demo:${{env.IMAGE_TAG}}
          format: table
          exit-code: "1"
          severity: CRITICAL,HIGH
      
      # ------------------------------------
      # Push only if scan passed
      # ------------------------------------

      - name: Push Image to ECR
        run: |
          ECR_URI=$(aws ecr describe-repositories \
            --repository-names ${{secrets.ECR_REPO}} \
            --query 'repositories[0].repositoryUri' \
            --output text) 
          docker tag fastapi-demo:${IMAGE_TAG} $ECR_URI:${IMAGE_TAG}
          docker push $ECR_URI:${IMAGE_TAG}

      - name: Test AWS auth
        run: aws sts get-caller-identity    
