name: FastAPI CI Pipeline Started.

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV  

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t fastapi-demo:${IMAGE_TAG} .
      # ------------------------------------
      # Trivy securityScan
      # ------------------------------------
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master

        with: 
          image-ref: fastapi-demo:${{env.IMAGE_TAG}}
          format: table
          exit-code: "1"
          severity: CRITICAL,HIGH
      
      # ------------------------------------
      # Push only if scan passed
      # ------------------------------------
      - name: Push Image to ECR
        run: |
          ECR_URI=$(aws ecr describe-repositories \
            --repository-names ${{secrets.ECR_REPO}} \
            --query 'repositories[0].repositoryUri' \
            --output text) 
          docker tag fastapi-demo:${IMAGE_TAG} $ECR_URI:${IMAGE_TAG}
          docker push $ECR_URI:${IMAGE_TAG}
      # -------------------------
      # Update GitOps Repo (Optimized)
      # -------------------------
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: amolwank/fastapi-gitops
          token: ${{ secrets.GITOPS_TOKEN }} # Recommended: Use a Personal Access Token or Deploy Key
          path: gitops-repo

      - name: Update Image Tag
        run: |
          cd gitops-repo
          # Use the env context to ensure the tag is captured correctly
          sed -i "s/tag:.*/tag: \"${{ env.IMAGE_TAG }}\"/" helm/fastapi/values.yaml
          
          git config --global user.email "ci@github.com"
          git config --global user.name "github-actions"
          
          git add helm/fastapi/values.yaml
          
          # Only commit and push if there are actual changes
          if git diff --staged --quiet; then
            echo "No changes to image tag. Skipping push."
          else
            git commit -m "Deploy FastAPI ${{ env.IMAGE_TAG }}"
            git push origin main
          fi

      - name: Test AWS auth
        run: aws sts get-caller-identity    

      
  