name: FastAPI CI Pipeline Started.

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV  

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t fastapi-demo:${IMAGE_TAG} .
      # ------------------------------------
      # Trivy securityScan
      # ------------------------------------
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master

        with: 
          image-ref: fastapi-demo:${{env.IMAGE_TAG}}
          format: table
          exit-code: "1"
          severity: CRITICAL,HIGH
      
      # ------------------------------------
      # Push only if scan passed
      # ------------------------------------
      - name: Push Image to ECR
        run: |
          ECR_URI=$(aws ecr describe-repositories \
            --repository-names ${{secrets.ECR_REPO}} \
            --query 'repositories[0].repositoryUri' \
            --output text) 
          docker tag fastapi-demo:${IMAGE_TAG} $ECR_URI:${IMAGE_TAG}
          docker push $ECR_URI:${IMAGE_TAG}
      # -------------------------
      # Update GitOps Repo
      # -------------------------
      name: FastAPI CI Pipeline Started.

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV  

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t fastapi-demo:${IMAGE_TAG} .
      # ------------------------------------
      # Trivy securityScan
      # ------------------------------------
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master

        with: 
          image-ref: fastapi-demo:${{env.IMAGE_TAG}}
          format: table
          exit-code: "1"
          severity: CRITICAL,HIGH
      
      # ------------------------------------
      # Push only if scan passed
      # ------------------------------------
      - name: Push Image to ECR
        run: |
          ECR_URI=$(aws ecr describe-repositories \
            --repository-names ${{secrets.ECR_REPO}} \
            --query 'repositories[0].repositoryUri' \
            --output text) 
          docker tag fastapi-demo:${IMAGE_TAG} $ECR_URI:${IMAGE_TAG}
          docker push $ECR_URI:${IMAGE_TAG}
      # -------------------------
      # Update GitOps Repo
      # -------------------------
      - name: Update GitOps Repo with new image tag
        env:
          GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "github-actions"

          # Tell git to use token for github.com
          git config --global url."https://${GITOPS_TOKEN}@github.com/".insteadOf "https://github.com/"

          git clone https://github.com/amolwank/fastapi-gitops.git
          cd fastapi-gitops

          sed -i "s/tag:.*/tag: \"${IMAGE_TAG}\"/" helm/fastapi/values.yaml

          git add helm/fastapi/values.yaml
          git commit -m "Deploy FastAPI ${IMAGE_TAG}"
          git push origin main


      - name: Test AWS auth
        run: aws sts get-caller-identity    

      
  